# When plugging in to my dock, it will detect an available audio output and
# switch the default sink to it, which I don't want because there's nothing
# actually connected. I think the reason is that the availability is listed as
# "unknown" rather than "not available".
monitor.alsa.rules = [
  {
    matches = [{ node.name = "~alsa_output.usb-Lenovo_ThinkPad_Thunderbolt*" }]
    actions = {
      update-props = {
        priority.session = 500
      }
    }
  }
]
