#!/usr/bin/env /bin/bash

mkdir -p ~/.config
target=~/.config/base16-shell
if [ -d "$target" ]; then
  (cd "$target" && git update)
else
  git clone https://github.com/chriskempson/base16-shell.git "$target"
fi

[ -s "$BASE16_SHELL/profile_helper.sh" ] && \
  eval "$("$BASE16_SHELL/profile_helper.sh")"

base16_tomorrow-night
