#!/usr/bin/env bash

fzf_dir=/usr/share/fzf
if [ -d $fzf_dir ]; then
  # Doesn't actually install fzf, just links the scripts
  cp $fzf_dir/key-bindings.bash ~/.fzf.bash
  cp $fzf_dir/key-bindings.zsh ~/.fzf.zsh
else
  echo "You must install fzf yourself first" >&2
  exit 1
fi
