#!/usr/bin/env bash
set -euo pipefail
set -x

cd "$(mktemp -d)"

# prereqs
sudo pacman -Sy base-devel gmp git

# paru
git clone https://aur.archlinux.org/paru-git.git
cd paru-git
makepkg -si

# pellets
paru -S pellets

# go
sudo pellets
