#!/usr/bin/env /bin/bash

dir=~/.zprezto

if [ -d "$dir" ]; then
  (cd "$dir" && git pull)
else
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "$dir"
fi

# Link non-source-controlled files
for f in zlogin zlogout zprofile zshenv; do
  ln -sf .zprezto/runcoms/$f ~/.$f
done
