#!/usr/bin/env bash

command=(aura -A --unsuppress --noconfirm --delmakedeps "$@")

# Drop back to user for building packages, which helps with signature
# verifcation
if [[ -n "$SUDO_USER" ]]; then
  exec su "$SUDO_USER" "${command[@]}"
else
  exec "${command[@]}"
fi
