#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Doug Patti"
email = "douglas.patti@gmail.com"

[ui]
default-command = "log"
pager = "delta"
diff-formatter = "delta"

[merge-tools.delta]
diff-expected-exit-codes = [0, 1]

[colors]
"diff token" = { bold = true, underline = false }
